channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::pip=25.0.1
  - conda-forge::python=3.11.11
  - conda-forge::setuptools=75.8
  - pip:
      - anndata==0.11.4
      - h5py==3.13
      - metaspace-converter==1.1.1
      - numcodecs==0.15.1
      - numpy==2.1.3
      - pandas==2.2.3
      - spatialdata==0.3.0
      - spatial_image==1.2.1
      - zarr==2.18.4
