---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::htslib=1.23
  - conda-forge::pip=26.0.1
  - conda-forge::python=3.14.3
  - pip:
      - gens-input-data-tools==2.0.1
